### ISSUE TITLE
Is it possible to split the rendering ?

### ISSUE THREAD

**Issue by CedricMaillot** [MewesK/TwigExcelBundle#11]
Hi,

I tried to do an XLS file with a tons of data, and it gives me an error 500 (I think it is a php memory limit).
I tried to embed the view rendering in a StreamedResponse, but it gives me an error 500 too, so my question is : 

**Is it possible to split de file.xls.twig so I can use an Doctrine  IterableResult to render the StreamedResponse row by row ?**

I don't know if actually it's posible to have a top.xls.twig with a starting tag {% xlsdocument %} and close it in another file ?

Thank you,

**Comment by MewesK** [comment]
The way PHPExcel works sadly doesn't allow streamed responses. Under the hood you always have to  first add all the data and then render it as a whole. The result may be streamed but that won't help you since the memory issues will occur before or while rendering.

I think the only way to fix this problem is to increase max memory usage or stream CSV manually.

After googling a little I read about cell caching in PHPExcel. I'll try to reduce the memory footprint for large worksheets to make this problem less common but that won't fix the problem in general.
