### ISSUE TITLE
Include another template

### ISSUE THREAD

**Issue by plfort** [MewesK/TwigExcelBundle#14]
Hello, does the bundle supports "include" tag (or is it  planned ?)

I get this error : Node "MewesK\TwigExcelBundle\Twig\Node\XlsCellNode" is not allowed inside of Node "" with this template : 

```
# file1.xls.twig
        {% xlsrow %}
            {% xlscell %}V1{% endxlscell %}
            {% xlscell %}V2{% endxlscell %}
            {% for item in items %}
                {% include 'file2.xls.twig' %}
            {% endfor %}
        {% endxlsrow %}

# file2.xls.twig

            {% xlscell %}V3{% endxlscell %}

```

**Comment by MewesK** [comment]
Hey @plfort, just replace 'include' with 'xlsinclude' and it should work. More info about that can be found in the documentation.

**Comment by plfort** [comment]
Hello @MewesK , I can't find any reference to this tag neither in documentation or in source code ...

**Comment by MewesK** [comment]
I'm sorry, just checked the docs. I've implemented xlsmacro but not xlsinclude (https://twigexcelbundle.readthedocs.io/en/latest/twig_tags.html#xlsmacro).

Give me a couple of days. I'll try to add this feature by the weekend.

**Comment by plfort** [comment]
It would be great, thank you !

**Comment by MewesK** [comment]
Wow, that took a while. Twig wasn't as cooperative as I hoped it would be. Since I have to clean the node tree I had to come up with a wrapper tag to control the included template. For an example take a look atr the docs: [https://twigexcelbundle.readthedocs.io/en/latest/twig_tags.html#xlsinclude](https://twigexcelbundle.readthedocs.io/en/latest/twig_tags.html#xlsinclude)

**Comment by plfort** [comment]
Thank you ! I'll try it asap
