### ISSUE TITLE
Attempted to load class "PHPExcel_Writer_" from the global namespace.

### ISSUE THREAD

**Issue by apatinor** [MewesK/TwigExcelBundle#3]
Hi, I found very interesting the bundle but I had a problem when used outside of the controller. I've created a service that handles Excel exports and the same call from the controller, but presents this error.
Attempted to load class "PHPExcel_Writer_" from the global namespace. Did you forget a "use" statement? 
in vendor/phpoffice/phpexcel/Classes/PHPExcel/IOFactory.php at line 141  -

```
            if ($searchLocation['type'] == $searchType) {
                $className = str_replace('{0}', $writerType, $searchLocation['class']);
                $instance = new $className($phpExcel);
                if ($instance !== NULL) {
                    return $instance;
                }
```

Is it not possible to use it outside of the controller?
here is my code:
in controller
    /**
     \* @Route("/reports/registration", name="registration")
     */
    public function reportRegistrationAction(Request $request)
    {
        $this->get('app.report_generator')->registrationPerformance();
    }
in service
    public function registrationPerformance()
    {
        $this->twig->render('reports/registration.html.twig', array('data' => array('la','le','li','lo','lu')));
    }
Thank's

**Comment by MewesK** [comment]
Hi,

the problem with your code is, that you haven't provided a valid format type. Since you are using 'reports/registration.html.twig' the format is 'html'. But you have to put the Twig tags of this bundle in a template with the extension '.xslx.twig', etc. or set the _format variable manually to 'xlsx', etc.

I will add this information more prominently to the README.md so other people won't face the same problem.

Greetings,
MewesK
