### ISSUE TITLE
Allow twig blocks usage

### ISSUE THREAD

**Issue by qcho** [MewesK/TwigExcelBundle#6]
It would be awesome if we can create something like:

```
{% xlsdocument %}
    {% xlssheet 'first' %}...{% endxlssheet %}
    {% block other_stuff %}{% endblock %}
{% endxlsdocument %}
```

And then

```
{% extends 'base_report.xls.twig' %}
{% block other_stuff %}
     {% xlssheet 'second' %}...{% endxlssheet %}
     {% xlssheet 'third' %}...{% endxlssheet %}
{% endblock %}
```

For nicer composition of reports.

It's throwing `Node "MewesK\TwigExcelBundle\Twig\Node\XlsSheetNode" is not allowed inside of Node "" in "QbicMainBundle:Accountancy:sharesReportSingle.xls.twig".`

**Comment by MewesK** [comment]
Yeah sounds nice, I'll look into it this weekend. Thanks for the suggestion.

**Comment by MewesK** [comment]
Wow, this feature is way more troublesome to implement than I've imagined. 

The first part (just defining the blocks for the first time) was actually quite easy to implement since we are already inside the xlsdocument tag. This way I can strip all the empty text nodes easily (the empty text nodes are just the indents used in the template). The big problem is the second part. The indent of 
`"     {% xlssheet 'second' %}"`
is outside of the scope I can manipulate easily. 

So to make it work I had to extend the normal Twig block to take full control. The downside is that the block tag is not working you have to use xlsblock. The upside is that I don't have to change the behavior of the default blocks so that I don't collide with the normal HTML based use-cases of Twig.

The basics are working fine now. But before I can merge it back into master and make a release I have to stabilize this feature. One thing is to do the same thing for Twig macros (just to be feature complete as much as possible). And the other thing is to extend the syntax checker to throw meaningful exceptions in case the features are used incorrectly (block instead of xlsblock for example).

Give me another week and this feature should be ready to release.

**Comment by qcho** [comment]
Too bad Twig did't give you sufficient control to implement normal blocks.
Great work figuring out a solution :D

**Comment by MewesK** [comment]
This feature can be found in the 2.0 release.

**Comment by qcho** [comment]
AWESOME!!! :D Thanks
